### ISSUE TITLE
tools.py THHT env error

### ISSUE THREAD

**Issue by lijiang2014** [lijiang2014/thht#16]
```
[mgkj_jchli_1@ln2%tianhe2-C THHT]$ ./tools.sh -s 
o ,a : -s 
Summary (-s) :
{'success': 0, 'tasks': 48, 'failure': 0}
[mgkj_jchli_1@ln2%tianhe2-C THHT]$ ./tools.sh -R 
o ,a : -R 
Running Tasks (-R) :
Traceback (most recent call last):
  File "/WORK/app/thht/thht/tools.py", line 232, in <module>
    data = c.running()
  File "/WORK/app/thht/thht/tools.py", line 71, in running
    from ht_celery.celery import app
  File "/WORK/app/thht/thht/ht_celery/__init__.py", line 8, in <module>
    raise Exception("Error: No THHT_HOST SET")
Exception: Error: No THHT_HOST SET
[mgkj_jchli_1@ln2%tianhe2-C THHT]$ 
```

**Comment by lijiang2014** [comment]
需要修正./tools.sh，从 JSON 中设定 ENV THHT_HOST
